/** 
 * AUTO-GENERATED BY MARKETPLACE-AUDIT
 * RE-RUN 'npm run audit:marketplace' TO REFRESH
 */
export const RECOMMENDED_SEARCH_RELAYS = [
  "wss://relay.plebeian.market",
  "wss://nostr.novacisko.cz"
];
